### ISSUE TITLE
expression reparsed for each vertex

### ISSUE THREAD

**Issue by aselle** [taikomatsu/SeExprMeshMaya#1]
You are constructing an expression instance (which reparses the expression). This makes the evaluation much slower. You want to do that only when the expression string changes outside the vertex loop.  However, treading is a little bit more tricky to do this. You need to give each thread a copy of the expression (the expression will be parsed once per thread per expression chnange).

**Comment by taikomatsu** [comment]
Thank you aselle.
I thought it's so slow, but I also thought it's faster than single-thread version.
I'd like to modify that for make much faster.
Did you mean threading is not recommended?

**Comment by aselle** [comment]
Threading can definitely be useful, but it is more difficult if you don't
reparse the expression. So if I had to choose between threading and
not-reparsing, I would do the not-reparsing first.

**Comment by taikomatsu** [comment]
Thank you for your opinion.
Originally, I was thinking the speed is not too slow in single-thread.
But I implemented closestPoint function, it became quite slow.
So I made it to multi-threading, but as you said, I saw the implementation is wrong.
I'll modify it to not-reparsing one.
And I'm going to find a better implementation for it again.

Thanks a lot, aselle!

**Comment by taikomatsu** [comment]
I modified code about re-parsing.
Latest version is parsed once per thread.
Thank you for the advice, aselle!!

**Comment by taikomatsu** [comment]
Oops.
I understood about this function just now... :p
